FROM maven:3.9.9-eclipse-temurin-23-alpine AS builder

WORKDIR /app

ADD demo/ .

RUN mvn clean install


FROM maven:3.9.9-eclipse-temurin-23-alpine

WORKDIR /app

EXPOSE 8080

COPY --from=builder /app/target/demo-0.0.1-SNAPSHOT.jar /app/app.jar

CMD ["java", "-jar", "/app/app.jar"]